### ISSUE TITLE
Erp Payment Terms displays code instead of text on mobile

### ISSUE THREAD

**Issue by ymabreu** [Saleslogix/argos-sample#10]
Hello. I am trying to get to display the text value of the Erp Payment Terms, but it displays the code. I tried the code below, but it isnt working. Can someone please help me? Thank you.

this.registerCustomization('detail', 'account_detail', {
at: function(row) { return row.name === 'ErpPaymentTerm'; },
type: 'modify',
value: {
	name: 'ErpPaymentTerm',					
	label: 'erp payment terms',
	property: 'ErpPaymentTerm',
	storageMode: 'text'
   }
});

**Comment by jbest84** [comment]
This is similar to #9 . The ErpPaymentTerm is added via a customization, so your customization will not have access to it through a registerCustomization. You will have to alter the prototype for the account detail view to get access to the full layout:

```
var orig = crm.Views.Account.Detail.prototype._createCustomizedLayout;
crm.Views.Account.Detail.prototype._createCustomizedLayout = function _createCustomizedLayout() {
    var customizedLayout = orig.apply(this, arguments);
    if (Array.isArray(customizedLayout)) {
        customizedLayout.forEach(function forEach(row) {
            // Search for row.name === 'ErpPaymentTerm' and modify it
        });
    }

    return customizedLayout;
};
```

**Comment by ymabreu** [comment]
Hi, thank you for your response. I am still unable to get to display the text. I have tried this examples below, but no luck. I dont know what I am missing or doing wrong.

var origEPT = crm.Views.Account.Detail.prototype._createCustomizedLayout;
			crm.Views.Account.Detail.prototype._createCustomizedLayout = function _createCustomizedLayout() {
				var customizedLayout = origEPT.apply(this, arguments);
				if (Array.isArray(customizedLayout)) {
					customizedLayout.forEach(function forEach(row) {
						if (row.name === "ErpPaymentTerm") {
							display: format.PicklistDataDisplayType.TEXT,
						}
					});
				}

				return customizedLayout;
			};
			


var origEPT = crm.Views.Account.Detail.prototype._createCustomizedLayout;
			crm.Views.Account.Detail.prototype._createCustomizedLayout = function _createCustomizedLayout() {
				var customizedLayout = origEPT.apply(this, arguments);
				if (Array.isArray(customizedLayout)) {
					customizedLayout.forEach(function forEach(row) {
						if (row.name === "moreDetailRowMatch") { // tried ErpPaymentTerm here too.
							renderer: this.formatPicklist('ErpPaymentTerm')							
						}
					});
				}

				return customizedLayout;
			};

var origEPT = crm.Views.Account.Detail.prototype._createCustomizedLayout;
			crm.Views.Account.Detail.prototype._createCustomizedLayout = function _createCustomizedLayout() {
				var customizedLayout = origEPT.apply(this, arguments);
				if (Array.isArray(customizedLayout)) {
					customizedLayout.forEach(function forEach(row) {
						if (row.name === "moreDetailRowMatch") {	// tried ErpPaymentTerm here too.						
							return format.picklist(this.app.picklistService, this._model, 'ErpPaymentTerm', undefined, undefined, {
								  display: format.PicklistDataDisplayType.TEXT,
								  storage: format.PicklistStorageType.CODE,
							});
						}
					});
				}

				return customizedLayout;
			};

**Comment by ymabreu** [comment]
Good morning. I still cant make the Payment Terms display the text. I have tried the below. It seems I continue doing something wrong. Now the change is no longer needed, but I just wanted to see it work. Thank you.

var origEPT = crm.Views.Account.Detail.prototype._createCustomizedLayout;
			crm.Views.Account.Detail.prototype._createCustomizedLayout = function _createCustomizedLayout() {
				var customizedLayout = origEPT.apply(this, arguments);
				if (Array.isArray(customizedLayout)) {
					customizedLayout.forEach(function forEach(row) {
						if (row.name === "moreDetailRowMatch") {
							row.property = "ErpPaymentTerm";
							return format.picklist(this.app.picklistService, this._model, 'ErpPaymentTerm', undefined, undefined, {
								display: format.PicklistDataDisplayType.TEXT,
								storage: format.PicklistStorageType.CODE,
							});
						}
					});
				}
				return customizedLayout;
			};

**Comment by jbest84** [comment]
You were close, the format.picklist function returns a function, so it must be invoked with the value from the row. To get the current value, you can create a renderer function.

```
    // argos-sample/issues/10
    const orig = crm.Views.Account.Detail.prototype._createCustomizedLayout;
    crm.Views.Account.Detail.prototype._createCustomizedLayout = function _createCustomizedLayout() {
      const customizedLayout = orig.apply(this, arguments);
      if (Array.isArray(customizedLayout)) {
        customizedLayout.forEach((row) => {
          // ErpPaymentTerm is a child of DetailsSection
          if (row.name === 'DetailsSection') {
            row.children.forEach((child) => {
              if (child.property === 'ErpPaymentTerm') {
                // Create a custom renderer property for the layout item
                child.renderer = function renderer(val) {
                  const picklistName = 'ErpPaymentTerm';
                  const property = '';
                  const picklistOptions = {
                    storage: ICRMCommonSDK.format.PicklistStorageType.CODE, /* CODE: 0, ID: 1, TEXT: 2 */
                    display: ICRMCommonSDK.format.PicklistDataDisplayType.TEXT, /* CODE: 0, ID: 1, TEXT: 2 */
                  };

                  // crm.Format.picklist returns a format function
                  const formatFunction = crm.Format.picklist(App.picklistService, this._model, property, picklistName, App.getCurrentLocale(), picklistOptions);
                  return formatFunction(val); // This could be immediately invoked instead of assigning to a variable on the line above
                };
              }
            });
          }
        });
      }

      return customizedLayout;
    };
```

**Comment by ymabreu** [comment]
Thank you very much for your time and help!
