### ISSUE TITLE
Creating an Opportunity from a ticket not setting the account correctly.

### ISSUE THREAD

**Issue by ymabreu** [Saleslogix/argos-sample#11]
Hi. Some help with the below issue would be highly appreciated. Thank you in advance.

On my ApplicationModule.js file I have the below code where I am attempting to click a button on the ticket details and create an opportunity that will have the Account and Contacts prefilled from the ticket on the insert Opportunity (opportunity_edit). I also need to set a user lookup to the current user on the opportunity. The fields are filled in, but when I click the save button on the opportunity edit, I get the error:  "message": "not-null property references a null or transient value Sage.SalesLogix.Entities.Opportunity.Account.". It looks like the controls have the values filled in, but they are not really setting the property. Do you know how could I achieve what I need?

registerTicketCustomizations: function() {
	//Quick action button for Create Opportunity.	
	this.registerCustomization('detail', 'ticket_detail', {
		at: function(row) { return row.action === 'scheduleActivity' },
		type: 'insert',
		where: 'after',
		value: {
			value: 'Add new Opportunity',					
			cls: 'action-list',
			label: 'Create Opportunity',
			iconClass: 'edit',				
			action: 'navigateToInsertOpportunity'						
		}
	});			
	//The Account and Contact on the Ticket will carry over to the Opportunity, and the Referred By field will default to the current user.
	lang.extend(crm.Views.Ticket.Detail, {
		navigateToInsertOpportunity: function() {
			var currentTicketId = this.entry.$key;
			var view = App.getView('opportunity_edit');					
			
			if (view) {
				//console.log('Opportunity fields before show:', view.fields);
				var currentUser = App.context && App.context.user;
				
				// Fetch the current Ticket data including Account and Contact information
				var request = new Sage.SData.Client.SDataSingleResourceRequest(App.getService())
					.setResourceKind('tickets')
					.setResourceSelector("'" + currentTicketId + "'")
					.setQueryArg('select', ['Account', 'Account/AccountName', 'Contact', 'Contact/NameLF'].join(','));

				request.read({
					success: function(ticketData) {
						//console.log('Ticket data fetched:', JSON.stringify(ticketData, null, 2)); // Log the entire object
						
						var account = ticketData.Account; // Get the account data
						var contact = ticketData.Contact; // Get the contact data
						
						// Show the opportunity edit view with the ReferredBy, Account, and Contacts fields pre-populated
						view.show({									
							template: {
								CloseProbability: 1,
								//EstimatedClose: estimatedCloseDate,
								ReferredBy: currentUser ? currentUser : null,																				
								Account: account ? {
									$key: account.$key,
									AccountName: account.AccountName // This ensures the lookup displays the Account Name. With &descriptor, the lookup displayed the account id.
								} : null,
								//Contacts: contact ? [contact] : []// this is not working so far.
							},									
							insert: true
						});	
						 view.fields.Account.setValue({
							"$key": account.$key,
							"AccountName": account.AccountName
						});
						view.fields.ReferredBy.setValue(currentUser ? currentUser : null);							
					},
					failure: function(err) {
						console.error('Failed to fetch ticket data:', err);
					}
				});						
			}
		}
	});
	
},

**Comment by jbest84** [comment]
@ymabreu  - What is the POST/PUT payload being sent to the server when you click save?

Also prior to clicking save, you can pop open the console and see how it is building up the values:

```
var v = App.getPrimaryActiveView();
v.getValues();
```

The source for this is in _EditBase:
https://github.com/Saleslogix/argos-sdk/blob/develop/src/_EditBase.js#L848

**Comment by ymabreu** [comment]
Hi, thank you for your response. I attached three images, one is the payload when I click save, another is the view values, and the last one is the code which I modified a bit to include viewing the values being built.


![payload](https://github.com/user-attachments/assets/120968b1-bc4f-4c59-a060-93f44f5fec58)

![image](https://github.com/user-attachments/assets/1863dcd1-0c67-431c-af26-831a76d17de2)

![image](https://github.com/user-attachments/assets/da660df0-33a2-4be3-8670-e7a1fb795958)

**Comment by jbest84** [comment]
@ymabreu - It looks like your POST is missing the Account field. In your code, try changing the view.show so that it passes an empty template object, and your desired entry. You can also remove the `view.fields.Account.setValue`

```
view.show({
  template: {},
  entry: {
    ReferredBy: currentUser ? currentUser : null,
    Account: {
      $key: account.$key,
      AccountName: account.AccountName,
    },
  },
  insert: true,
});
```

When you get to the insert opportunity view. You can ensure the field is dirty:
```
var v = App.getPrimaryActiveView();
v.fields.Account.isDirty();
```

This should return true, and now the Account should be part of the POST.

**Comment by ymabreu** [comment]
Using the 'entry' part did it. Thank you so so much!

![image](https://github.com/user-attachments/assets/2754fb4a-7b13-4b2c-9a89-804ccde01ee5)

**Comment by jbest84** [comment]
You are welcome! Have a good day.

**Comment by ymabreu** [comment]
Thank you! You too!
