### ISSUE TITLE
return lookup not loading anything

### ISSUE THREAD

**Issue by ymabreu** [Saleslogix/argos-sample#12]
Hello. I have the below code for a return lookup on ticket edit. When I click it, no data is loaded, nothing happens. Similarly, I have one for Sales Orders. That one was initially the same, not loading anything. I had to enable BOE in order for the Sales Order lookup to load orders. Is there something I have to enable in order for returns to load or do I have to create a view under my project views? Thank you.

//Return lookup
this.registerCustomization('edit', 'ticket_edit', {
    at: function(row) {
	    return row.name === 'StatusCode'
    },
    type: 'insert',
    where: 'after',
    value: {
	    label: 'rma',
	    name: 'RMA',
	    textProperty: 'ReturnNumber',
	    property: 'RMA',
	    type: 'lookup',
	    view: 'returns_list', // not working
	    requireSelection: false					
    },				
});

//Sales Order lookup
this.registerCustomization('edit', 'ticket_edit', {
    at: function(row) {
	    return row.name === 'StatusCode'
    },
    type: 'insert',
    where: 'after',
    value: {
	    label: 'order #',
	    name: 'SalesOrder',
	    textProperty: 'SalesOrderNumber',
	    property: 'SalesOrder',
	    type: 'lookup',
	    view: 'salesorder_list' //'account_salesorders_related'													
    },				
});

**Comment by jbest84** [comment]
Yes the returns_list is located in crm.Integrations.BOE.Views.Returns.List. If you don't want to enable BOE, you can import this in your application module, and register it there. Once registered it should get loaded into the Application view list.

**Comment by ymabreu** [comment]
Hi. Thank you for your response. I do have BOE enabled, but the Return lookup isn’t loading any results with the above code. However, the Sales Order lookup is working as expected. Am I missing something?

**Comment by jbest84** [comment]
It looks like the BOE module doesn't use that list. In your app module, import "crm/Integrations/BOE/Views/Returns/List" and assign that to a ReturnsList variable.

example:
```
define(['crm/Integrations/BOE/Views/Returns/List', function(ReturnsList) {...});
```

In your application module's loadView, add this:

```
this.registerView(
        new ReturnsList({
          id: 'returns_list',
          groupsEnabled: false,
          expose: false,
        })
      );
```

You might want to override the `itemTemplate` property in that returns listview to make it easier to read. 

To debug these kind of issues, you can open the console and type in `App.getView('<VIEW ID>')`. This should return the view. If it is undefined chances are the ID is wrong, or the view is not registered in the module!

**Comment by ymabreu** [comment]
Thank you for pointing me to the right path. It is working now! Have a nice weekend!

**Comment by jbest84** [comment]
You are welcome. Have a good one.
